### PR TITLE
allow-either-image-url-or-link-2

### LINKED ISSUE #2: Allow either the link URL and the image URL to be passed to the obrowser
Currently when over an image that is linked, the context menu code sends the link URL to the object browser. Make it so that you have a choice between the link URL and the image URL. This will allow people to tag the image URL, which I think is going to be teh awesome

### PR DESCRIPTION
**Pull request by terrycojones**
ntoll:approve paparent:approve

Added context menu for page, image URL, frame. Made code simpler and more explicit.

Fixes #2

### CODE REVIEW

**Comment by ntoll** [comment]
Code looks good, I downloaded the extension and it works as advertised. Yay! +1000000000000000000000

**Comment by paparent** [comment]
+1 ! Cool works well!

1) the URLs are encoded (/ is %2F). We already talked about that for my bookmarklet. Is it what we want ?

**Comment by terrycojones** [comment]
Yes, %-encoded URLs in the request that's sent to fluidinfo.com is fine. They're being decoded properly by Django and our Python is seeing the value with slashes, which is what we want.  Thanks!

**Comment by paparent** [comment]
Cool, I'll re-edit my bookmarklet ;)

**Comment by terrycojones** [comment]
Merge allow-either-image-url-or-link-2: Added context menu for page, image URL, and frame.
Author: terry
Reviewer: ntoll, paparent
Fixes #2

**Pull request merged**
