### PR TITLE
stop-using-new.fluidinfo.com-96

### LINKED ISSUE #96: Change sidebar URL from new.fi.com to fi.com
The sidebar is loading its content from new.fi.com.  For release we'll want this to be fi.com

### PR DESCRIPTION
**Pull request by terrycojones**
paparent:**approved**

NOTE: don't merge until fluidinfo.com can serve the infomaniac sidebar content correctly.

TRIVIAL: Move to fi.com from new.fi.com

Fixes #96

### CODE REVIEW

**Comment by paparent** [comment]
+1 very nice branch :)

**Comment by ntoll** [comment]
ZOMG. +1

**Comment by terrycojones** [comment]
I will update this once https://github.com/fluidinfo/obrowser-chrome-extension/pull/106 has landed.

**Comment by terrycojones** [comment]
Done in a trivial against the new code base.

**Pull request closed without merging**
